#!/usr/bin/env python3
"""
Prove the pinned tinygrad still carries the NV-USB eGPU patch.

The eGPU needs an NVIDIA card on a USB3 bridge. CI has none, and neither does the desk this
was written on. What *can* be checked without hardware is that the patch is structurally
intact: the classes it introduces are defined, the backend it adds is registered in the list
the device actually selects from, and every file it touched still parses.

Deliberately no `import tinygrad.runtime.ops_nv` here. That pulls in the autogenerated NVIDIA
headers and the rest of the dependency tree, and on a runner with no NVIDIA device the import
that succeeds tells you nothing and the one that fails tells you nothing either. AST and
compile() answer the question that is actually being asked.

Checks 7 and 8 need no checkout at all -- they prove the registries in overlay.py are
self-consistent, so a sixth file added to the allowlist cannot quietly widen it with nothing
watching the new file.

Usage:
    python .elantra/test_egpu_tinygrad.py                      # registry consistency only
    python .elantra/test_egpu_tinygrad.py --tinygrad <path>    # + inspect the patch itself
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from overlay import (
    NV_DELTA_PATHS, NV_DEVICE_METHOD, NV_IFACE_REGISTRY, NV_SENTINEL_EXEMPT, NV_SENTINELS,
)

CONFLICT_MARKER = re.compile(r"^(<{7}|>{7}) ", re.MULTILINE)

_failures: list[str] = []
_passes: list[str] = []


def check(label: str, condition: bool, detail: str = "") -> None:
    suffix = ": " + detail if detail else ""
    if condition:
        _passes.append(label)
        print("  ok    " + label)
    else:
        _failures.append(label + suffix)
        print("  FAIL  " + label + suffix)


def defined(source: str) -> set[tuple[str, str]]:
    """(kind, name) for every class and function defined anywhere in a module."""
    out: set[tuple[str, str]] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ClassDef):
            out.add(("class", node.name))
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            out.add(("def", node.name))
    return out


def class_list_attr(source: str, cls: str, attr: str) -> list[str] | None:
    """The Name elements of `attr = [...]` inside class `cls`, or None if the class is absent.

    None and [] are different answers: "the class is gone" and "the class is there with the
    wrong contents" are different failures and deserve different messages.
    """
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ClassDef) and node.name == cls:
            for stmt in node.body:
                if isinstance(stmt, ast.Assign) and any(
                        isinstance(t, ast.Name) and t.id == attr for t in stmt.targets):
                    if isinstance(stmt.value, ast.List | ast.Tuple):
                        return [e.id for e in stmt.value.elts if isinstance(e, ast.Name)]
                    return []
            return []
    return None


def class_methods(source: str, cls: str) -> list[str] | None:
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ClassDef) and node.name == cls:
            return [b.name for b in node.body
                    if isinstance(b, ast.FunctionDef | ast.AsyncFunctionDef)]
    return None


def check_registries() -> None:
    """Runs without a checkout. Guards the guard."""
    print("\n[registry] overlay.py is self-consistent")
    unknown = sorted(set(NV_SENTINELS) - set(NV_DELTA_PATHS))
    check("every sentinel file is in the delta allowlist", not unknown, ", ".join(unknown))

    unwatched = sorted(set(NV_DELTA_PATHS) - set(NV_SENTINELS) - set(NV_SENTINEL_EXEMPT))
    check("every delta file has a sentinel or a stated exemption", not unwatched,
          ", ".join(unwatched) + " -- add a sentinel, or say in NV_SENTINEL_EXEMPT why not")

    both = sorted(set(NV_SENTINELS) & set(NV_SENTINEL_EXEMPT))
    check("no file is both watched and exempt", not both, ", ".join(both))

    check("the iface registry check targets a delta file",
          NV_IFACE_REGISTRY[0] in NV_DELTA_PATHS, NV_IFACE_REGISTRY[0])
    check("the device method check targets a delta file",
          NV_DEVICE_METHOD[0] in NV_DELTA_PATHS, NV_DEVICE_METHOD[0])


def check_patch(tinygrad: Path) -> None:
    print("\n[patch] the NV-USB delta is intact in " + str(tinygrad))

    sources: dict[str, str] = {}
    for rel in NV_DELTA_PATHS:
        target = tinygrad / rel
        if not target.is_file():
            check(rel + " exists", False, "the delta touched it; a rename upstream dropped it")
            continue
        check(rel + " exists", True)
        sources[rel] = target.read_text(encoding="utf-8", errors="replace")

    for rel, src in sources.items():
        check(rel + " has no conflict markers", not CONFLICT_MARKER.search(src),
              "a three-way apply can return 0 and still leave these behind")

    # The highest-value no-hardware check: a three-way apply that produced plausible garbage
    # dies here rather than on the car.
    for rel, src in sources.items():
        try:
            compile(src, rel, "exec")
            check(rel + " compiles", True)
        except SyntaxError as e:
            check(rel + " compiles", False, "line " + str(e.lineno) + ": " + str(e.msg))

    for rel, wanted in NV_SENTINELS.items():
        if rel not in sources:
            continue
        try:
            found = defined(sources[rel])
        except SyntaxError:
            continue  # already reported by the compile check
        for kind, name in wanted:
            check(rel + ": " + kind + " " + name + " defined", (kind, name) in found,
                  "the NV-USB delta did not survive the replay onto sunnypilot's tinygrad")

    rel, cls, attr, want = NV_IFACE_REGISTRY
    if rel in sources:
        ifaces = class_list_attr(sources[rel], cls, attr)
        check(cls + "." + attr + " exists", ifaces is not None,
              "the NV device class was restructured upstream; this guard no longer checks anything")
        if ifaces is not None:
            check(want + " is registered in " + cls + "." + attr, want in ifaces,
                  "the USB backend is defined but nothing will ever select it; found "
                  + str(ifaces))

    rel, cls, meth = NV_DEVICE_METHOD
    if rel in sources:
        methods = class_methods(sources[rel], cls)
        check(cls + "." + meth + "() is a method of " + cls,
              methods is not None and meth in methods,
              "the allocator's USB path branches on this; a reindented method still compiles")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tinygrad", type=Path, default=None,
                    help="tinygrad checkout to inspect (default: registry checks only)")
    args = ap.parse_args()

    print("eGPU tinygrad patch checks")
    check_registries()

    if args.tinygrad:
        tinygrad = args.tinygrad.resolve()
        if not (tinygrad / "tinygrad/runtime/ops_nv.py").is_file():
            raise SystemExit("not a tinygrad checkout: " + str(tinygrad))
        check_patch(tinygrad)
    else:
        print("\nnote: no --tinygrad checkout given; the patch itself was NOT inspected.")
        print("      Only the registry consistency checks ran.")

    print("\n" + "-" * 60)
    if _failures:
        print("FAILED: " + str(len(_failures)) + " check(s) failed, "
              + str(len(_passes)) + " passed\n")
        for f in _failures:
            print("  - " + f)
        print("\nThe pinned tinygrad does not carry working eGPU support. Nothing should be")
        print("published against it.")
        return 1
    print("PASSED: all " + str(len(_passes)) + " checks green.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
