#!/usr/bin/env python3
"""
Prove the pinned tinygrad still carries the NV-USB eGPU patch.

The eGPU needs an NVIDIA card on a USB3 bridge. CI has none, and neither does the desk this
was written on. What *can* be checked without hardware is that the patch is structurally
intact: the classes it introduces are defined, the backend it adds is registered in the list
the device actually selects from, and every file it touched still parses.

Deliberately no `import tinygrad.runtime.ops_nv` here. That pulls in the autogenerated NVIDIA
headers and the rest of the dependency tree, and on a runner with no NVIDIA device the import
that succeeds tells you nothing and the one that fails tells you nothing either. AST and
compile() answer the question that is actually being asked.

Checks 7 and 8 need no checkout at all -- they prove the registries in overlay.py are
self-consistent, so a sixth file added to the allowlist cannot quietly widen it with nothing
watching the new file.

Usage:
    python .elantra/test_egpu_tinygrad.py                      # registry consistency only
    python .elantra/test_egpu_tinygrad.py --tinygrad <path>    # + inspect the patch itself
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from openpilot.sunnypilot.egpu.asics import UNSUPPORTED_AMD
from overlay import (
    NV_DELTA_PATHS, NV_DEVICE_METHOD, NV_IFACE_REGISTRY, NV_SENTINEL_EXEMPT, NV_SENTINELS,
)

CONFLICT_MARKER = re.compile(r"^(<{7}|>{7}) ", re.MULTILINE)

_failures: list[str] = []
_passes: list[str] = []


def check(label: str, condition: bool, detail: str = "") -> None:
    suffix = ": " + detail if detail else ""
    if condition:
        _passes.append(label)
        print("  ok    " + label)
    else:
        _failures.append(label + suffix)
        print("  FAIL  " + label + suffix)


def defined(source: str) -> set[tuple[str, str]]:
    """(kind, name) for every class and function defined anywhere in a module."""
    out: set[tuple[str, str]] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ClassDef):
            out.add(("class", node.name))
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            out.add(("def", node.name))
    return out


def class_list_attr(source: str, cls: str, attr: str) -> list[str] | None:
    """The Name elements of `attr = [...]` inside class `cls`, or None if the class is absent.

    None and [] are different answers: "the class is gone" and "the class is there with the
    wrong contents" are different failures and deserve different messages.
    """
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ClassDef) and node.name == cls:
            for stmt in node.body:
                if isinstance(stmt, ast.Assign) and any(
                        isinstance(t, ast.Name) and t.id == attr for t in stmt.targets):
                    if isinstance(stmt.value, ast.List | ast.Tuple):
                        return [e.id for e in stmt.value.elts if isinstance(e, ast.Name)]
                    return []
            return []
    return None


def class_methods(source: str, cls: str) -> list[str] | None:
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ClassDef) and node.name == cls:
            return [b.name for b in node.body
                    if isinstance(b, ast.FunctionDef | ast.AsyncFunctionDef)]
    return None


def check_registries() -> None:
    """Runs without a checkout. Guards the guard."""
    print("\n[registry] overlay.py is self-consistent")
    unknown = sorted(set(NV_SENTINELS) - set(NV_DELTA_PATHS))
    check("every sentinel file is in the delta allowlist", not unknown, ", ".join(unknown))

    unwatched = sorted(set(NV_DELTA_PATHS) - set(NV_SENTINELS) - set(NV_SENTINEL_EXEMPT))
    check("every delta file has a sentinel or a stated exemption", not unwatched,
          ", ".join(unwatched) + " -- add a sentinel, or say in NV_SENTINEL_EXEMPT why not")

    both = sorted(set(NV_SENTINELS) & set(NV_SENTINEL_EXEMPT))
    check("no file is both watched and exempt", not both, ", ".join(both))

    check("the iface registry check targets a delta file",
          NV_IFACE_REGISTRY[0] in NV_DELTA_PATHS, NV_IFACE_REGISTRY[0])
    check("the device method check targets a delta file",
          NV_DEVICE_METHOD[0] in NV_DELTA_PATHS, NV_DEVICE_METHOD[0])


def check_patch(tinygrad: Path) -> None:
    print("\n[patch] the NV-USB delta is intact in " + str(tinygrad))

    sources: dict[str, str] = {}
    for rel in NV_DELTA_PATHS:
        target = tinygrad / rel
        if not target.is_file():
            check(rel + " exists", False, "the delta touched it; a rename upstream dropped it")
            continue
        check(rel + " exists", True)
        sources[rel] = target.read_text(encoding="utf-8", errors="replace")

    for rel, src in sources.items():
        check(rel + " has no conflict markers", not CONFLICT_MARKER.search(src),
              "a three-way apply can return 0 and still leave these behind")

    # The highest-value no-hardware check: a three-way apply that produced plausible garbage
    # dies here rather than on the car.
    for rel, src in sources.items():
        try:
            compile(src, rel, "exec")
            check(rel + " compiles", True)
        except SyntaxError as e:
            check(rel + " compiles", False, "line " + str(e.lineno) + ": " + str(e.msg))

    for rel, wanted in NV_SENTINELS.items():
        if rel not in sources:
            continue
        try:
            found = defined(sources[rel])
        except SyntaxError:
            continue  # already reported by the compile check
        for kind, name in wanted:
            check(rel + ": " + kind + " " + name + " defined", (kind, name) in found,
                  "the NV-USB delta did not survive the replay onto sunnypilot's tinygrad")

    rel, cls, attr, want = NV_IFACE_REGISTRY
    if rel in sources:
        ifaces = class_list_attr(sources[rel], cls, attr)
        check(cls + "." + attr + " exists", ifaces is not None,
              "the NV device class was restructured upstream; this guard no longer checks anything")
        if ifaces is not None:
            check(want + " is registered in " + cls + "." + attr, want in ifaces,
                  "the USB backend is defined but nothing will ever select it; found "
                  + str(ifaces))

    rel, cls, meth = NV_DEVICE_METHOD
    if rel in sources:
        methods = class_methods(sources[rel], cls)
        check(cls + "." + meth + "() is a method of " + cls,
              methods is not None and meth in methods,
              "the allocator's USB path branches on this; a reindented method still compiles")



def gfx_major(gfx: str) -> int:
    """The major version out of an LLVM target name.

    tinygrad builds these as `"gfx%d%x%x" % target` (ops_amd.py), so the last two characters
    are minor and revision in hex and everything before them is the major: gfx1032 -> 10.
    """
    return int(gfx[len("gfx"):-2])


def supported_am_targets(source: str) -> tuple[set[int], set[tuple[int, ...]]] | None:
    """(supported gfx majors, exactly-supported targets) as ops_amd.py itself declares them.

    Read off the assert rather than restated, because restating it is exactly the mistake
    this check exists to catch. Matched by AST so reflowing the line changes nothing.
    """
    for node in ast.walk(ast.parse(source)):
        if not isinstance(node, ast.Assert) or node.msg is None:
            continue
        msg = ast.dump(node.msg)
        if "Unsupported arch" not in msg:
            continue
        majors: set[int] = set()
        exact: set[tuple[int, ...]] = set()
        for cmp_node in ast.walk(node.test):
            if not isinstance(cmp_node, ast.Compare) or not isinstance(cmp_node.ops[0], ast.In):
                continue
            right = cmp_node.comparators[0]
            if not isinstance(right, ast.Tuple):
                continue
            if isinstance(cmp_node.left, ast.Subscript):        # self.target[0] in (11, 12)
                majors |= {e.value for e in right.elts if isinstance(e, ast.Constant)}
            else:                                                # self.target in ((9,4,2), ...)
                for elt in right.elts:
                    if isinstance(elt, ast.Tuple):
                        exact.add(tuple(e.value for e in elt.elts if isinstance(e, ast.Constant)))
        return majors, exact
    return None


def check_am_arch(tinygrad: Path) -> None:
    """Our blocklist must agree with what tinygrad's AM driver actually refuses.

    egpu/asics.py decides whether a card gets the driving model. It is a hand-written table,
    and the thing it is a table *of* lives in tinygrad and moves. If RDNA2 support ever lands
    upstream, the table silently starts switching off eGPUs that would now work -- a failure
    that looks like nothing at all. So derive the truth from the source on every run.
    """
    print("\n[am] the RDNA2 blocklist still matches what AM refuses")
    ops_amd = tinygrad / "tinygrad/runtime/ops_amd.py"
    if not ops_amd.is_file():
        check("ops_amd.py exists", False, "cannot verify the arch table against anything")
        return

    declared = supported_am_targets(ops_amd.read_text(encoding="utf-8", errors="replace"))
    check("ops_amd.py still asserts which architectures AM supports", declared is not None,
          "our whole gate is derived from that assert; without it we are guessing")
    if declared is None:
        return

    majors, exact = declared
    print("        AM supports gfx majors " + str(sorted(majors))
          + " plus exact targets " + str(sorted(exact)))
    check("AM still supports at least one architecture", bool(majors or exact))

    blocked = {gfx_major(spec.gfx) for spec in UNSUPPORTED_AMD.values()}
    check("nothing in our blocklist is an architecture AM supports",
          not (blocked & majors),
          "asics.py blocks gfx major(s) " + str(sorted(blocked & majors))
          + " that tinygrad now drives -- delete those entries")
    check("our blocklist is not empty", bool(UNSUPPORTED_AMD))
    check("every blocked entry names a real gfx target",
          all(spec.gfx.startswith("gfx") and spec.gfx[3:].isalnum()
              for spec in UNSUPPORTED_AMD.values()))

    # Stage 1 of the RDNA2 port adds gfx10.3 register tables on purpose, so their presence is no
    # longer evidence of anything. What matters is the ordering: registers may land ahead of the
    # assert, never behind it. If the assert ever admits major 10 while the blocklist still names
    # gfx10 parts, the check above goes red -- which is the intended way for the blocklist to be
    # retired: a card actually runs first, then the entry goes.
    regs = tinygrad / "tinygrad/runtime/autogen/am/regs.py"
    if regs.is_file():
        first = regs.read_text(encoding="utf-8", errors="replace").split(chr(10), 1)[0]
        have_gc = set(re.findall(r"gc_(\d+)_", first))
        if "10" in have_gc:
            check("gfx10 registers exist, so AM must still refuse gfx10.3 at the assert",
                  10 not in majors and not any(t[0] == 10 for t in exact),
                  "registers alone are not support; the blocklist stays until a card runs")
        else:
            print("        no gc_10_* register set yet (port stage 1 not applied to this tree)")


def check_gfx_target_table(tinygrad: Path) -> None:
    """gfx10's IP version and its gfx target are different numbers.

    tinygrad packed the three GC IP digits into gfx_target_version. That happens to work on
    gfx9/11/12 and is simply wrong on gfx10: five of the seven GC 10.3.x versions map to a
    different target, and not even monotonically -- 10.3.2 is gfx1031 while 10.3.4 is gfx1032.
    The failure is silent, because packing yields a *plausible* target for a different ASIC,
    and the card would then be compiled for the wrong ISA. Values are the kernel's, from
    drivers/gpu/drm/amd/amdkfd/kfd_device.c.
    """
    print("\n[am] GC IP version -> gfx target")
    ops_amd = tinygrad / "tinygrad/runtime/ops_amd.py"
    if not ops_amd.is_file():
        check("ops_amd.py exists", False)
        return
    src = ops_amd.read_text(encoding="utf-8", errors="replace")

    tree = ast.parse(src)
    table = None
    for node in ast.walk(tree):
        if (isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "GFX_TARGET_VERSION"
                                                 for t in node.targets)):
            table = ast.literal_eval(node.value)
    check("ops_amd.py defines a real GC -> gfx target table", table is not None,
          "without it gfx10 targets are digit-packed, which is wrong for RDNA2")
    if table is None:
        return

    # The card in the dock. Getting this one wrong compiles for Navi 24 and runs on Navi 23.
    for ip, want, name in (((10, 3, 4), 100302, "Dimgrey Cavefish is gfx1032"),
                           ((10, 3, 2), 100301, "Navy Flounder is gfx1031"),
                           ((10, 3, 5), 100304, "Beige Goby is gfx1034")):
        label = f"GC {ip[0]}.{ip[1]}.{ip[2]}: {name}"
        check(label, table.get(ip) == want, "got " + repr(table.get(ip)))

    # Decode exactly as ops_amd does, and confirm the arch string comes out right.
    def arch_of(trgt):
        return f"gfx{trgt // 10000:d}{(trgt // 100) % 100:x}{trgt % 100:x}"
    check("GC 10.3.4 renders as gfx1032", arch_of(table[(10, 3, 4)]) == "gfx1032",
          "got " + arch_of(table[(10, 3, 4)]))

    # The table has to actually disagree with packing, or it is not earning its place.
    def packed(ip):
        return int(f"{ip[0]:02d}{ip[1]:02d}{ip[2]:02d}")
    differs = {ip for ip, t in table.items() if packed(ip) != t}
    check("the table differs from digit-packing where it must",
          {(10, 3, 1), (10, 3, 2), (10, 3, 3), (10, 3, 4), (10, 3, 5), (10, 3, 7)} <= differs,
          "sorted(differs)=" + str(sorted(differs)))

    # Every gfx10 target the table produces must be a target our blocklist knows about, or the
    # two tables have drifted apart.
    blocked_gfx = {spec.gfx for spec in UNSUPPORTED_AMD.values()}
    rdna2 = {arch_of(t) for ip, t in table.items() if ip[:2] == (10, 3)}
    check("every gfx10.3 target the table can produce is in the blocklist or is an APU",
          blocked_gfx >= (rdna2 & {"gfx1030", "gfx1031", "gfx1032", "gfx1034"}),
          "blocklist=" + str(sorted(blocked_gfx)))


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tinygrad", type=Path, default=None,
                    help="tinygrad checkout to inspect (default: registry checks only)")
    args = ap.parse_args()

    print("eGPU tinygrad patch checks")
    check_registries()

    if args.tinygrad:
        tinygrad = args.tinygrad.resolve()
        if not (tinygrad / "tinygrad/runtime/ops_nv.py").is_file():
            raise SystemExit("not a tinygrad checkout: " + str(tinygrad))
        check_patch(tinygrad)
        check_am_arch(tinygrad)
        check_gfx_target_table(tinygrad)
    else:
        print("\nnote: no --tinygrad checkout given; the patch itself was NOT inspected.")
        print("      Only the registry consistency checks ran.")

    print("\n" + "-" * 60)
    if _failures:
        print("FAILED: " + str(len(_failures)) + " check(s) failed, "
              + str(len(_passes)) + " passed\n")
        for f in _failures:
            print("  - " + f)
        print("\nThe pinned tinygrad does not carry working eGPU support. Nothing should be")
        print("published against it.")
        return 1
    print("PASSED: all " + str(len(_passes)) + " checks green.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
