#!/usr/bin/env python3
"""
Prove the pinned tinygrad still carries the NV-USB eGPU patch.

The eGPU needs an NVIDIA card on a USB3 bridge. CI has none, and neither does the desk this
was written on. What *can* be checked without hardware is that the patch is structurally
intact: the classes it introduces are defined, the backend it adds is registered in the list
the device actually selects from, and every file it touched still parses.

Deliberately no `import tinygrad.runtime.ops_nv` here. That pulls in the autogenerated NVIDIA
headers and the rest of the dependency tree, and on a runner with no NVIDIA device the import
that succeeds tells you nothing and the one that fails tells you nothing either. AST and
compile() answer the question that is actually being asked.

Checks 7 and 8 need no checkout at all -- they prove the registries in overlay.py are
self-consistent, so a sixth file added to the allowlist cannot quietly widen it with nothing
watching the new file.

Usage:
    python .elantra/test_egpu_tinygrad.py                      # registry consistency only
    python .elantra/test_egpu_tinygrad.py --tinygrad <path>    # + inspect the patch itself
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))
sys.path.insert(0, str(Path(__file__).resolve().parent))
from openpilot.sunnypilot.egpu.asics import UNSUPPORTED_AMD
from overlay import (
    NV_DELTA_PATHS, NV_DEVICE_METHOD, NV_IFACE_REGISTRY, NV_SENTINEL_EXEMPT, NV_SENTINELS,
)

# gfx majors we block in asics.py even though AM drives them, and why. See check_am_arch.
BLOCKED_PENDING_VALIDATION = {
    # A Navi 23 runs kernels (sum -> 6, 64x64 ones matmul -> 262144). validate_numerics.py has
    # not been run against a real segment, and wrong-but-finite model output is what the
    # blocklist is actually protecting against.
    10: "kernels run; numerical validation against a real segment has not",
}

CONFLICT_MARKER = re.compile(r"^(<{7}|>{7}) ", re.MULTILINE)

_failures: list[str] = []
_passes: list[str] = []


def check(label: str, condition: bool, detail: str = "") -> None:
    suffix = ": " + detail if detail else ""
    if condition:
        _passes.append(label)
        print("  ok    " + label)
    else:
        _failures.append(label + suffix)
        print("  FAIL  " + label + suffix)


def defined(source: str) -> set[tuple[str, str]]:
    """(kind, name) for every class and function defined anywhere in a module."""
    out: set[tuple[str, str]] = set()
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ClassDef):
            out.add(("class", node.name))
        elif isinstance(node, ast.FunctionDef | ast.AsyncFunctionDef):
            out.add(("def", node.name))
    return out


def class_list_attr(source: str, cls: str, attr: str) -> list[str] | None:
    """The Name elements of `attr = [...]` inside class `cls`, or None if the class is absent.

    None and [] are different answers: "the class is gone" and "the class is there with the
    wrong contents" are different failures and deserve different messages.
    """
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ClassDef) and node.name == cls:
            for stmt in node.body:
                if isinstance(stmt, ast.Assign) and any(
                        isinstance(t, ast.Name) and t.id == attr for t in stmt.targets):
                    if isinstance(stmt.value, ast.List | ast.Tuple):
                        return [e.id for e in stmt.value.elts if isinstance(e, ast.Name)]
                    return []
            return []
    return None


def class_methods(source: str, cls: str) -> list[str] | None:
    for node in ast.walk(ast.parse(source)):
        if isinstance(node, ast.ClassDef) and node.name == cls:
            return [b.name for b in node.body
                    if isinstance(b, ast.FunctionDef | ast.AsyncFunctionDef)]
    return None


def check_registries() -> None:
    """Runs without a checkout. Guards the guard."""
    print("\n[registry] overlay.py is self-consistent")
    unknown = sorted(set(NV_SENTINELS) - set(NV_DELTA_PATHS))
    check("every sentinel file is in the delta allowlist", not unknown, ", ".join(unknown))

    unwatched = sorted(set(NV_DELTA_PATHS) - set(NV_SENTINELS) - set(NV_SENTINEL_EXEMPT))
    check("every delta file has a sentinel or a stated exemption", not unwatched,
          ", ".join(unwatched) + " -- add a sentinel, or say in NV_SENTINEL_EXEMPT why not")

    both = sorted(set(NV_SENTINELS) & set(NV_SENTINEL_EXEMPT))
    check("no file is both watched and exempt", not both, ", ".join(both))

    check("the iface registry check targets a delta file",
          NV_IFACE_REGISTRY[0] in NV_DELTA_PATHS, NV_IFACE_REGISTRY[0])
    check("the device method check targets a delta file",
          NV_DEVICE_METHOD[0] in NV_DELTA_PATHS, NV_DEVICE_METHOD[0])


def check_patch(tinygrad: Path) -> None:
    print("\n[patch] the NV-USB delta is intact in " + str(tinygrad))

    sources: dict[str, str] = {}
    for rel in NV_DELTA_PATHS:
        target = tinygrad / rel
        if not target.is_file():
            check(rel + " exists", False, "the delta touched it; a rename upstream dropped it")
            continue
        check(rel + " exists", True)
        sources[rel] = target.read_text(encoding="utf-8", errors="replace")

    for rel, src in sources.items():
        check(rel + " has no conflict markers", not CONFLICT_MARKER.search(src),
              "a three-way apply can return 0 and still leave these behind")

    # The highest-value no-hardware check: a three-way apply that produced plausible garbage
    # dies here rather than on the car.
    for rel, src in sources.items():
        try:
            compile(src, rel, "exec")
            check(rel + " compiles", True)
        except SyntaxError as e:
            check(rel + " compiles", False, "line " + str(e.lineno) + ": " + str(e.msg))

    for rel, wanted in NV_SENTINELS.items():
        if rel not in sources:
            continue
        try:
            found = defined(sources[rel])
        except SyntaxError:
            continue  # already reported by the compile check
        for kind, name in wanted:
            check(rel + ": " + kind + " " + name + " defined", (kind, name) in found,
                  "the NV-USB delta did not survive the replay onto sunnypilot's tinygrad")

    rel, cls, attr, want = NV_IFACE_REGISTRY
    if rel in sources:
        ifaces = class_list_attr(sources[rel], cls, attr)
        check(cls + "." + attr + " exists", ifaces is not None,
              "the NV device class was restructured upstream; this guard no longer checks anything")
        if ifaces is not None:
            check(want + " is registered in " + cls + "." + attr, want in ifaces,
                  "the USB backend is defined but nothing will ever select it; found "
                  + str(ifaces))

    rel, cls, meth = NV_DEVICE_METHOD
    if rel in sources:
        methods = class_methods(sources[rel], cls)
        check(cls + "." + meth + "() is a method of " + cls,
              methods is not None and meth in methods,
              "the allocator's USB path branches on this; a reindented method still compiles")



def gfx_major(gfx: str) -> int:
    """The major version out of an LLVM target name.

    tinygrad builds these as `"gfx%d%x%x" % target` (ops_amd.py), so the last two characters
    are minor and revision in hex and everything before them is the major: gfx1032 -> 10.
    """
    return int(gfx[len("gfx"):-2])


def supported_am_targets(source: str) -> tuple[set[int], set[tuple[int, ...]], set[tuple[int, ...]]] | None:
    """(gfx majors, exact targets, target prefixes) as ops_amd.py itself declares them.

    Read off the assert rather than restated, because restating it is exactly the mistake
    this check exists to catch. Matched by AST so reflowing the line changes nothing.
    """
    for node in ast.walk(ast.parse(source)):
        if not isinstance(node, ast.Assert) or node.msg is None:
            continue
        msg = ast.dump(node.msg)
        if "Unsupported arch" not in msg:
            continue
        majors: set[int] = set()
        exact: set[tuple[int, ...]] = set()
        prefixes: set[tuple[int, ...]] = set()
        for cmp_node in ast.walk(node.test):
            if not isinstance(cmp_node, ast.Compare):
                continue
            right = cmp_node.comparators[0]
            if not isinstance(right, ast.Tuple):
                continue
            if isinstance(cmp_node.ops[0], ast.Eq):
                # self.target[:2] == (10,3) -- a whole family admitted by prefix. Reading only
                # `in` comparisons made this form invisible, so widening the assert this way
                # slipped past the very check that exists to notice it.
                if isinstance(cmp_node.left, ast.Subscript) and isinstance(cmp_node.left.slice, ast.Slice):
                    prefixes.add(tuple(e.value for e in right.elts if isinstance(e, ast.Constant)))
                continue
            if not isinstance(cmp_node.ops[0], ast.In):
                continue
            if isinstance(cmp_node.left, ast.Subscript):        # self.target[0] in (11, 12)
                majors |= {e.value for e in right.elts if isinstance(e, ast.Constant)}
            else:                                                # self.target in ((9,4,2), ...)
                for elt in right.elts:
                    if isinstance(elt, ast.Tuple):
                        exact.add(tuple(e.value for e in elt.elts if isinstance(e, ast.Constant)))
        return majors, exact, prefixes
    return None


def check_am_arch(tinygrad: Path) -> None:
    """Our blocklist must agree with what tinygrad's AM driver actually refuses.

    egpu/asics.py decides whether a card gets the driving model. It is a hand-written table,
    and the thing it is a table *of* lives in tinygrad and moves. If RDNA2 support ever lands
    upstream, the table silently starts switching off eGPUs that would now work -- a failure
    that looks like nothing at all. So derive the truth from the source on every run.
    """
    print("\n[am] the RDNA2 blocklist still matches what AM refuses")
    ops_amd = tinygrad / "tinygrad/runtime/ops_amd.py"
    if not ops_amd.is_file():
        check("ops_amd.py exists", False, "cannot verify the arch table against anything")
        return

    declared = supported_am_targets(ops_amd.read_text(encoding="utf-8", errors="replace"))
    check("ops_amd.py still asserts which architectures AM supports", declared is not None,
          "our whole gate is derived from that assert; without it we are guessing")
    if declared is None:
        return

    majors, exact, prefixes = declared
    print("        AM supports gfx majors " + str(sorted(majors))
          + " plus exact targets " + str(sorted(exact))
          + " plus prefixes " + str(sorted(prefixes)))
    check("AM still supports at least one architecture", bool(majors or exact or prefixes))

    am_majors = majors | {p[0] for p in prefixes} | {t[0] for t in exact}
    blocked = {gfx_major(spec.gfx) for spec in UNSUPPORTED_AMD.values()}

    # Blocking something AM can drive is allowed, because the driver working is not the same
    # claim as the model producing correct output -- a kernel returning 6 says nothing about a
    # 1.76 GB pickle over a real segment. But it has to be deliberate: an unexplained over-block
    # is how a table quietly starts switching off eGPUs that would now work, which is the exact
    # failure this whole check was written for. Emptying this map is what retires an entry, and
    # nothing should empty it before .elantra/validate_numerics.py has passed on that card.
    unexplained = (blocked & am_majors) - set(BLOCKED_PENDING_VALIDATION)
    check("every architecture we block that AM now drives has a stated reason",
          not unexplained,
          "asics.py blocks gfx major(s) " + str(sorted(unexplained))
          + " that tinygrad now drives, with no entry in BLOCKED_PENDING_VALIDATION")
    stale = set(BLOCKED_PENDING_VALIDATION) - (blocked & am_majors)
    check("no stale entries in BLOCKED_PENDING_VALIDATION", not stale,
          "these are no longer both blocked and driveable: " + str(sorted(stale)))
    check("our blocklist is not empty", bool(UNSUPPORTED_AMD))
    check("every blocked entry names a real gfx target",
          all(spec.gfx.startswith("gfx") and spec.gfx[3:].isalnum()
              for spec in UNSUPPORTED_AMD.values()))

    # Stage 1 of the RDNA2 port adds gfx10.3 register tables on purpose, so their presence is no
    # longer evidence of anything. What matters is the ordering: registers may land ahead of the
    # assert, never behind it. If the assert ever admits major 10 while the blocklist still names
    # gfx10 parts, the check above goes red -- which is the intended way for the blocklist to be
    # retired: a card actually runs first, then the entry goes.
    regs = tinygrad / "tinygrad/runtime/autogen/am/regs.py"
    if regs.is_file():
        first = regs.read_text(encoding="utf-8", errors="replace").split(chr(10), 1)[0]
        have_gc = set(re.findall(r"gc_(\d+)_", first))
        if "10" in have_gc:
            # Registers may land ahead of the assert, never behind it. That ordering held while
            # the port was unfinished; a Navi 23 has since run kernels, so the assert admits
            # (10,3) and the invariant that remains is the blocklist not quietly disappearing
            # with it.
            admits_gfx10 = 10 in am_majors
            if admits_gfx10:
                check("AM admits gfx10.3, so the blocklist must still be there and explained",
                      10 in blocked and 10 in BLOCKED_PENDING_VALIDATION,
                      "a card running kernels does not retire the entry -- numerical validation does")
            else:
                check("gfx10 registers exist, so AM must still refuse gfx10.3 at the assert",
                      not any(t[0] == 10 for t in exact),
                      "registers alone are not support; the blocklist stays until a card runs")
        else:
            print("        no gc_10_* register set yet (port stage 1 not applied to this tree)")


def check_gfx_target_table(tinygrad: Path) -> None:
    """gfx10's IP version and its gfx target are different numbers.

    tinygrad packed the three GC IP digits into gfx_target_version. That happens to work on
    gfx9/11/12 and is simply wrong on gfx10: five of the seven GC 10.3.x versions map to a
    different target, and not even monotonically -- 10.3.2 is gfx1031 while 10.3.4 is gfx1032.
    The failure is silent, because packing yields a *plausible* target for a different ASIC,
    and the card would then be compiled for the wrong ISA. Values are the kernel's, from
    drivers/gpu/drm/amd/amdkfd/kfd_device.c.
    """
    print("\n[am] GC IP version -> gfx target")
    ops_amd = tinygrad / "tinygrad/runtime/ops_amd.py"
    if not ops_amd.is_file():
        check("ops_amd.py exists", False)
        return
    src = ops_amd.read_text(encoding="utf-8", errors="replace")

    tree = ast.parse(src)
    table = None
    for node in ast.walk(tree):
        if (isinstance(node, ast.Assign) and any(isinstance(t, ast.Name) and t.id == "GFX_TARGET_VERSION"
                                                 for t in node.targets)):
            table = ast.literal_eval(node.value)
    check("ops_amd.py defines a real GC -> gfx target table", table is not None,
          "without it gfx10 targets are digit-packed, which is wrong for RDNA2")
    if table is None:
        return

    # The card in the dock. Getting this one wrong compiles for Navi 24 and runs on Navi 23.
    for ip, want, name in (((10, 3, 4), 100302, "Dimgrey Cavefish is gfx1032"),
                           ((10, 3, 2), 100301, "Navy Flounder is gfx1031"),
                           ((10, 3, 5), 100304, "Beige Goby is gfx1034")):
        label = f"GC {ip[0]}.{ip[1]}.{ip[2]}: {name}"
        check(label, table.get(ip) == want, "got " + repr(table.get(ip)))

    # Decode exactly as ops_amd does, and confirm the arch string comes out right.
    def arch_of(trgt):
        return f"gfx{trgt // 10000:d}{(trgt // 100) % 100:x}{trgt % 100:x}"
    check("GC 10.3.4 renders as gfx1032", arch_of(table[(10, 3, 4)]) == "gfx1032",
          "got " + arch_of(table[(10, 3, 4)]))

    # The table has to actually disagree with packing, or it is not earning its place.
    def packed(ip):
        return int(f"{ip[0]:02d}{ip[1]:02d}{ip[2]:02d}")
    differs = {ip for ip, t in table.items() if packed(ip) != t}
    check("the table differs from digit-packing where it must",
          {(10, 3, 1), (10, 3, 2), (10, 3, 3), (10, 3, 4), (10, 3, 5), (10, 3, 7)} <= differs,
          "sorted(differs)=" + str(sorted(differs)))

    # Every gfx10 target the table produces must be a target our blocklist knows about, or the
    # two tables have drifted apart.
    blocked_gfx = {spec.gfx for spec in UNSUPPORTED_AMD.values()}
    rdna2 = {arch_of(t) for ip, t in table.items() if ip[:2] == (10, 3)}
    check("every gfx10.3 target the table can produce is in the blocklist or is an APU",
          blocked_gfx >= (rdna2 & {"gfx1030", "gfx1031", "gfx1032", "gfx1034"}),
          "blocklist=" + str(sorted(blocked_gfx)))



# --- Phase 2 stage 2.0: RDNA2 register-name resolution ---------------------------------------
#
# gfx10-era AMD headers spell every register mm*; gfx11 and later spell them reg*. AM is written
# entirely in reg*, and AMDev.reg() is a bare __dict__ lookup, so on a Navi 2x card not one
# register resolves until an alias layer exists. Counting generated registers does not catch
# this -- stage 1 generated 1271 gc registers and zero of them were reachable under the names AM
# asks for. These checks test the thing that actually matters: the names, not the count.

# What AMDev._build_regs resolves for this card's reported IP versions.
RDNA2_MODULES = (("gc", (10, 3, 4)), ("mp", (11, 0, 12)), ("hdp", (5, 0, 3)),
                 ("mmhub", (2, 1, 1)), ("osssys", (5, 0, 3)), ("nbio", (3, 3, 2)))

# Strings AM passes as a *base* to wreg_pair() or an f-string, not whole register names. Each is
# checked with its real suffixes instead.
RDNA2_PREFIXES = {
    "regMP0_SMN_C2PMSG": ("_35", "_36", "_64", "_67", "_69", "_70", "_71", "_81"),
    "regIH_RB_WPTR_ADDR": ("_LO", "_HI"),
}

# Names AM references that must NOT resolve on gfx10.3. Keeping this exact matters both ways: one
# that starts resolving means the alias table grew something it should not have, and one that
# stops being referenced means this list is stale. The value says why -- either the call site is
# already correctly version-guarded away from gfx10.3, or it is a guard a later stage has to fix.
RDNA2_EXPECTED_ABSENT = {
    "regXCC_DOORBELL_FENCE": "MI300 multi-XCC; guarded on NBIO 7.9 at ip.py:31",
    "regBIFC_GFX_INT_MONITOR_MASK": "MI300 nbio 7.9; guarded at ip.py:31",
    "regBIFC_DOORBELL_ACCESS_EN_PF": "MI300 nbio 7.9; guarded at ip.py:31",
    "regTCP_UTCL1_CNTL2": "MI300 golden reg; guarded on GC 9.4.3/9.5.0 at ip.py:278",
    "regMMMC_VM_XGMI_LFB_CNTL": "XGMI is MI-series; hasattr-guarded at ip.py:55",
    "regMMMC_VM_XGMI_LFB_SIZE": "XGMI is MI-series; hasattr-guarded at ip.py:56",
    "regBIF_BX_PF0_RSMU_INDEX": "RSMU is MI-series; nbio 2.3 uses PCIE_INDEX2 (stage 3)",
    "regBIF_BX_PF0_RSMU_DATA": "RSMU is MI-series; nbio 2.3 uses PCIE_DATA2 (stage 3)",
    "regBIF_BX0_PCIE_INDEX2_HI": "nbio 4.3+ only; reached only when hi32(addr) > 0",
    "regCP_MEC_RS64_CNTL": "RS64 is gfx11+; gfx10.3 starts MEC via CP_MEC_CNTL (stage 4)",
    "regTCP_CNTL": "gfx11 golden reg, written unconditionally at ip.py:264 (stage 4 must guard)",
    "regIH_MSI_STORM_CTRL": "absent on OSSSYS 5.0; guard at ip.py:431 is wrong (stage 3)",
    "regRCC_DEV0_EPF2_STRAP2": "nbio 4.3 / nbif 6.3 only; guard at ip.py:37 is wrong (stage 3)",
    "regSDMA0_RLC_CGCG_CTRL": "not in the gc 10.3 header; guard at ip.py:361 is wrong (stage 3)",
    "regSDMA1_RLC_CGCG_CTRL": "not in the gc 10.3 header; guard at ip.py:361 is wrong (stage 3)",
    # f-string bases for paths gfx10.3 does not take. They are whole strings in the source,
    # so they show up in the scan, but no register is ever built from them on this card.
    "regMPASP_SMN_C2PMSG": "PSP mailbox prefix for MP0 14+; 11.0.12 uses regMP0_SMN_C2PMSG",
    "regGDC_S2A0_S2A": "doorbell prefix for GC 12+; gfx10.3 takes the regS2A branch",
    "regS2A": "doorbell prefix; nbio 2.3 has BIF_{SDMA0,SDMA1,IH}_DOORBELL_RANGE instead (stage 3)",
    "regSDMA_GFX": "ring prefix for MI300 SDMA 4.4; 5.2.4 takes regSDMA{i}_QUEUE{q}, whose registers are also absent until regs.py is regenerated (stage 5)",
}

_REG_PROBE = r'''
import ast, functools, json, re, sys
sys.path.insert(0, sys.argv[1])
from tinygrad.runtime.support.amd import AMDReg, import_asic_regs, import_module

# Only register *names* are under test, so no real IP bases are needed.
NOBASE = functools.partial(AMDReg, bases={})

MODULES = json.loads(sys.argv[2])
NAME = re.compile(r"reg[A-Z][A-Za-z0-9_]*")

# Every whole reg* name AM references. Constants inside an f-string are fragments, not names.
static = set()
for rel in ("tinygrad/runtime/support/am/ip.py", "tinygrad/runtime/support/am/amdev.py"):
    tree = ast.parse(open(sys.argv[1] + "/" + rel).read())
    frag = {id(v) for n in ast.walk(tree) if isinstance(n, ast.JoinedStr)
            for v in n.values if isinstance(v, ast.Constant)}
    for n in ast.walk(tree):
        if isinstance(n, ast.Attribute) and NAME.fullmatch(n.attr):
            static.add(n.attr)
        elif isinstance(n, ast.Constant) and id(n) not in frag \
                and isinstance(n.value, str) and NAME.fullmatch(n.value):
            static.add(n.value)

resolved, per_module = {}, {}
for prefix, ver in MODULES:
    raw = import_module(prefix, tuple(ver), submod="regs")
    aliased = import_asic_regs(prefix, tuple(ver), cls=NOBASE)
    per_module[prefix] = {
        "raw": len(raw),
        "raw_mm": sum(1 for k in raw if k.startswith("mm")),
        "aliased": len(aliased),
        "unaliased_mm": sorted(k for k in raw if k.startswith("mm") and "reg" + k[2:] not in aliased),
    }
    resolved.update(dict.fromkeys(aliased, prefix))

# gfx11 is the control: it is already reg*-keyed, so aliasing must be a no-op on it.
gfx11_raw = import_module("gc", (11, 0, 0), submod="regs")
gfx11_aliased = import_asic_regs("gc", (11, 0, 0), cls=NOBASE)

print(json.dumps({
    "static": sorted(static),
    "have": sorted(resolved),
    "per_module": per_module,
    "gfx11_noop": len(gfx11_raw) == len(gfx11_aliased),
}))
'''


def _run_reg_probe(tinygrad: Path) -> dict | None:
    """Resolve registers in a subprocess so importing tinygrad cannot disturb the AST checks."""
    modules = json.dumps([[p, list(v)] for p, v in RDNA2_MODULES])
    with tempfile.TemporaryDirectory() as td:
        script = Path(td) / "reg_probe.py"
        script.write_text(_REG_PROBE, encoding="utf-8")
        proc = subprocess.run([sys.executable, str(script), str(tinygrad), modules],
                              capture_output=True, text=True)
    if proc.returncode != 0:
        tail = (proc.stderr or proc.stdout).strip().splitlines()
        check("the RDNA2 register probe runs", False, tail[-1] if tail else "no output")
        return None
    return json.loads(proc.stdout)


def check_rdna2_registers(tinygrad: Path) -> None:
    print("\nRDNA2 register-name resolution (Navi 23 / gfx1032):")
    if (probe := _run_reg_probe(tinygrad)) is None:
        return

    have = set(probe["have"])

    # 1. Every mm* register is reachable under the reg* name AM uses. This is also what makes the
    #    45 f-string call sites work, without having to enumerate them.
    unaliased = {p: d["unaliased_mm"] for p, d in probe["per_module"].items() if d["unaliased_mm"]}
    check("every mm* register is aliased to its reg* name", not unaliased,
          "unaliased: " + str({p: v[:3] for p, v in unaliased.items()}))

    # 2. The nbio registers that were renamed outright, not just re-spelled.
    for name in ("regBIF_BX0_BIF_DOORBELL_INT_CNTL", "regBIF_BX0_REMAP_HDP_MEM_FLUSH_CNTL",
                 "regBIF_BX0_PCIE_INDEX2", "regBIF_BX0_PCIE_DATA2"):
        check("nbio rename resolves: " + name, name in have)

    # 3. Every whole register name AM references resolves, unless it is expected-absent.
    names = set(probe["static"]) - set(RDNA2_PREFIXES) - set(RDNA2_EXPECTED_ABSENT)
    missing = sorted(n for n in names if n not in have)
    check("every register AM names resolves on gfx10.3", not missing,
          str(len(missing)) + " missing, e.g. " + str(missing[:5]))

    # 4. wreg_pair and f-string bases resolve with their real suffixes.
    bad = [b + s for b, sufs in RDNA2_PREFIXES.items() for s in sufs if b + s not in have]
    check("wreg_pair and f-string register bases resolve", not bad, str(bad[:5]))

    # 5. The expected-absent list is exact in both directions.
    leaked = sorted(n for n in RDNA2_EXPECTED_ABSENT if n in have)
    check("no MI300/gfx11-only register resolves on gfx10.3", not leaked,
          "these must not exist here: " + str(leaked))
    stale = sorted(set(RDNA2_EXPECTED_ABSENT) - set(probe["static"]))
    check("the expected-absent list has no stale entries", not stale,
          "no longer referenced by AM: " + str(stale))

    # 6. gfx11 is the negative control: already reg*-keyed, so aliasing must not touch it.
    check("aliasing is a no-op on gfx11 (already reg*-keyed)", probe["gfx11_noop"])


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--tinygrad", type=Path, default=None,
                    help="tinygrad checkout to inspect (default: registry checks only)")
    args = ap.parse_args()

    print("eGPU tinygrad patch checks")
    check_registries()

    if args.tinygrad:
        tinygrad = args.tinygrad.resolve()
        if not (tinygrad / "tinygrad/runtime/ops_nv.py").is_file():
            raise SystemExit("not a tinygrad checkout: " + str(tinygrad))
        check_patch(tinygrad)
        check_am_arch(tinygrad)
        check_gfx_target_table(tinygrad)
        check_rdna2_registers(tinygrad)
    else:
        print("\nnote: no --tinygrad checkout given; the patch itself was NOT inspected.")
        print("      Only the registry consistency checks ran.")

    print("\n" + "-" * 60)
    if _failures:
        print("FAILED: " + str(len(_failures)) + " check(s) failed, "
              + str(len(_passes)) + " passed\n")
        for f in _failures:
            print("  - " + f)
        print("\nThe pinned tinygrad does not carry working eGPU support. Nothing should be")
        print("published against it.")
        return 1
    print("PASSED: all " + str(len(_passes)) + " checks green.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
